apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: portworx-client
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8443
    targetPort: 8443
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: portworx-client
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: calvarado2004/portworx-client-keycloak:latest
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "change_me"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres/keycloak"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: "testpassword" 
        ports:
        - name: http
          containerPort: 8443
        readinessProbe:
          exec:
            command:
              - sh
              - -ec
              - 'curl -k -s https://127.0.0.1:8443/realms/master || exit 1'
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 2Gi