apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: portworx-client
  labels:
    app: keycloak
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: portworx-client
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
      - name: docker-hub
      containers:
      - name: keycloak
        image: calvarado2004/portworx-client-keycloak:latest
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "change_me"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres/keycloak"
        - name: KC_DB_USERNAME
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: "testpassword" 
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "http://localhost:8080/auth"
        - name: KC_HOSTNAME_URL
          value: "http://localhost:8080/auth"
        ports:
        - name: https
          containerPort: 8443
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth
            port: 8080
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: portworx-client
type: Opaque
data:
  keycloakClientID: cG9ydHdvcngtY2xpZW50
  keycloakRealm: cG9ydHdvcng=
  keycloakSecret: cjdaYndzcEJUNTZwUDVCNWNNTlNZd3l3S0l1dzN5U3M=
  keycloakUrl: aHR0cDovL2tleWNsb2FrOjgwODA=
