apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: portworx-client-frontend-bc
  namespace: portworx-client
  labels:
    app: portworx-client-frontend-bc
spec:
  source:
    type: Git
    git:
      uri: https://github.com/camartinez04/portworx-client
    contextDir: frontend
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: frontend.dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: portworx-client-frontend:latest

# oc create is portworx-client-frontend -n portworx-client

